version: '3'

services:
  openai:
    # See https://aka.ms/vscode-remote/containers/non-root for details.
    user: vscode
    build: 
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        VARIANT: 3.11-bullseye
        USER_UID: 1000
        USER_GID: 1000
    volumes:
      - ..:/workspace:cached

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
